Multi-stage pipeline introspection documentation
CatalystCode/spk pull request #118
Opened 2019-11-06 19:07 UTC by edaena

2019-11-06 19:30 UTC, sarath-p approved these changes
Looks good.

2019-11-08 18:44 UTC, samiyaakhtar requested changes

2019-11-08 18:44 UTC, samiyaakhtar commented on docs/service-introspection-onboarding.md
> +$(Build.BuildId)
As far as I can see, all this diff is doing is adding extra lines between the yaml, which will fail the bash task. You might want to fix the new lines. Other than the new lines, i don't see a diff here

2019-11-08 18:44 UTC, samiyaakhtar commented on docs/service-introspection-onboarding.md
> +$tag_name
Same here, new lines are going to cause this bash task to fail if the user just copy pastes it

2019-11-08 18:44 UTC, samiyaakhtar commented
@edaena I think we already seem to have documentation in place for multi-stage pipelines, right?

2019-11-14 21:20 UTC, samiyaakhtar commented on docs/service-introspection-onboarding.md
> +latest_commit=$(git rev-parse --short HEAD) VERSION_TO_DOWNLOAD=$(curl -s
New line between `VERSION_TO_DOWNLOAD` and `latest_commit=$(git rev-parse --short HEAD)`

2019-11-14 21:20 UTC, samiyaakhtar commented on docs/service-introspection-onboarding.md
> +"tag_name" | sed -E 's/.*"([^"]+)".*/\1/') echo "Downloading SPK version
Newline before echo as well

2019-11-14 21:21 UTC, samiyaakhtar commented on docs/service-introspection-onboarding.md
> +$(Build.BuildId)
@edaena I think this is still valid, may want to remove this diff altogether

2019-11-14 21:28 UTC, samiyaakhtar approved these changes

2019-11-14 22:14 UTC, merged