Consolidate documentation in spk code base
CatalystCode/spk pull request #134
Opened 2019-11-13 19:01 UTC by yradsmikham

2019-11-13 19:05 UTC, andrebriggs requested changes
It would be good to have a table of contents for the infra section such that docs like `spk-terragrunt-infra.md` are discoverable. Perhaps at `docs/infra/README.md` we have a bulleted list of all the docs in the `docs/infra/*` directory

2019-11-13 21:00 UTC, andrebriggs commented
The only other thing I would suggestis add a reference to `docs/infra/README.md` from `docs/cloud-infra-management.md`. Otherwise looks good

2019-11-13 21:00 UTC, andrebriggs approved these changes

2019-11-14 18:03 UTC, samiyaakhtar approved these changes
That's a lot of great documentation, thanks for writing it 👍

2019-11-14 18:04 UTC, edaena approved these changes

2019-11-14 18:04 UTC, edaena commented on docs/infra/README.md
> +There has been several design iterations for Cluster/Infrastructure creation and
nit: is it "have" been instead of has been?

2019-11-14 18:15 UTC, merged