First pass at "getting started with spk" docs
CatalystCode/spk pull request #193
Opened 2020-01-18 02:36 UTC by mtarng

Will need to follow up with some TBD sections that are labeled, but I wanted to get this into master as a starter reference.

Part of https://github.com/microsoft/bedrock/issues/747

2020-01-18 02:37 UTC, mtarng commented
Please share opinions on formatting and the structure of this guide!

2020-01-18 06:12 UTC, dennisseah requested changes

2020-01-18 06:12 UTC, dennisseah commented on docs/getting-started.md
> +This repository holds all the bedrock "High Level Defenition" (HLD) yaml files
"Defenition" typo

2020-01-18 06:12 UTC, dennisseah commented on docs/getting-started.md
> +manifests output by fabrikate are placed into the Materialied Manifests
"Materialied" typo

2020-01-18 18:44 UTC, dennisseah commented on docs/getting-started.md
> +- Variable Groups (Read, create, & manage)
I stop using full access and use these permissions. And it works ok. thanks

2020-01-21 21:17 UTC, dennisseah approved these changes

2020-01-24 19:34 UTC, evanlouie approved these changes
looks good so far 👍

2020-01-24 23:35 UTC, merged