CLI - Project - Add Service, create directory and add starter pipelin…
CatalystCode/spk pull request #20
Opened 2019-09-24 22:31 UTC by mtarng

…es.yaml file

initial PR for https://github.com/microsoft/bedrock/issues/577

2019-09-24 22:37 UTC, evanlouie requested changes

2019-09-24 22:37 UTC, evanlouie commented on src/commands/project/add-service.ts
> +import mkdirp from "mkdirp";
should keep on using shelljs instead. you can do `shell.mkdir('-p', 'your-dir')`

2019-09-24 22:37 UTC, evanlouie commented on src/commands/project/add-service.ts
> +// npm install @types/mkdirp
dont need

2019-09-24 22:37 UTC, evanlouie commented on src/commands/project/add-service.ts
> +  mkdirp(`${newServiceDir}`, function(err) {
use `shell.mkdir('-p', newServiceDir)` instead

2019-09-24 22:37 UTC, evanlouie commented on package.json
> +    "@types/mkdirp": "^0.5.2",
remove

2019-09-24 22:37 UTC, evanlouie commented on package.json
> +    "@types/mkdirp": "^0.5.2",
Actually not sure how this is working because we dont have `mkdirp` as a dependency

2019-09-25 15:21 UTC, timfpark requested changes
Let's agree on a common grammar for commands across the different teams - otherwise looks great to me.

2019-09-25 15:21 UTC, timfpark commented on src/commands/project/add-service.ts
> +    .command("add-service <service-name>")
For the `deployment` command, we separate nouns and verbs into two separate parts, eg.

`spk deployment get`

but here we are combining them into one eg.:

`spk add-service`

I would propose that we agree on one way of doing this and one common set of verbs (where possible) such that the cli feels like a coherent whole in the same way that the `kubectl` tool does despite having been developed by hundreds of engineers.

2019-09-25 18:41 UTC, evanlouie requested changes

2019-09-25 18:41 UTC, evanlouie commented on src/commands/project/add-service.ts
> +export const addService = async (
Add some JSDoc please 🙏 
We should standardize on having all export/public functions/classes on having some accompanying docs

2019-09-25 20:40 UTC, mtarng commented on src/commands/project/add-service.ts
> +    .command("add-service <service-name>")
This command was initially under `spk project add-service`, but after speaking with @evanlouie we're moving service creation/management under it's own command; now it's `spk service create` etc.

2019-09-25 21:02 UTC, evanlouie approved these changes

2019-09-25 21:04 UTC, bnookala approved these changes

2019-09-25 21:06 UTC, merged