Add condition based introspection scripts to pipelines
CatalystCode/spk pull request #217
Opened 2020-01-27 23:43 UTC by samiyaakhtar

Closes https://github.com/microsoft/bedrock/issues/621

2020-01-27 23:48 UTC, andrebriggs requested changes
Unit tests?

2020-01-28 00:00 UTC, andrebriggs commented
Test failure in the build

2020-01-28 00:17 UTC, mtarng reviewed
i wonder if we can make the variables a bit more descriptive, as in, they’re related to introspection:
`ACCOUNT_NAME` -> `SPEKTATE_ACCOUNT_NAME` or `DEPLOY_STATUS_ACCOUNT_NAME`
especially if these values will live in a variable group in the future. Keeps things clear on what each variable is for,

2020-01-28 00:21 UTC, mtarng commented on src/lib/fileutils.ts
> +                    "Download Fabrikate, Update HLD, Push changes, Open PR, optionally push to Spektate storage",
"Download Fabrikate, Update HLD, Push changes, Open PR, and if configured, push to Spektate storage"

2020-01-28 00:21 UTC, mtarng commented on src/lib/fileutils.ts
> +        displayName: "Update manifest pipeline details in Spektate db",
"If configured, update manifest pipeline details in Spektate db"

2020-01-28 00:35 UTC, edaena commented on src/lib/fileutils.ts
> +                    "Download Fabrikate, Update HLD, Push changes, Open PR, optionally push to Spektate storage",
Should we mention this in the introspection documentation? I'm thinking it can go in the getting started with introspection guide.

2020-01-28 01:37 UTC, mtarng approved these changes

2020-01-28 20:53 UTC, andrebriggs commented
@samiyaakhtar Looks good. One nit pick is not to use the prefix `SPEKTATE_` for variable names

2020-01-28 20:53 UTC, andrebriggs approved these changes

2020-01-30 18:19 UTC, merged