Removed duplicate call to check for bedrock file that enforces project commands order
CatalystCode/spk pull request #235
Opened 2020-01-30 21:21 UTC by sarath-p

- Closes https://github.com/microsoft/bedrock/issues/927

- Also merged `constants.ts` files.

2020-01-30 21:59 UTC, dennisseah requested changes

2020-01-30 21:59 UTC, dennisseah commented on src/lib/bedrockYaml.ts
> +export const fileInfo = async (
need not be an `async` function

2020-01-30 21:59 UTC, dennisseah commented on src/lib/bedrockYaml.ts
> +    logger.debug(
can be better written as
```
const bedrockFile = read(absProjectPath);
```

and remove
```
let bedrockFile: IBedrockFile | undefined;
```
avoiding the `undefined`

2020-01-30 22:26 UTC, dennisseah approved these changes
LGTM

2020-01-31 21:04 UTC, dennisseah approved these changes

2020-01-31 21:34 UTC, mtarng requested changes

2020-01-31 21:34 UTC, mtarng commented on src/lib/constants.ts
> +export const projectInitDependencyErrorMessage =
Can these variable names be changed to match the all uppercase convention?

ie. PROJECT_INIT_DEPENDENCY_ERROR_MESSAGE.

or something similar?

2020-01-31 22:36 UTC, mtarng approved these changes

2020-01-31 22:56 UTC, merged