Added visualstudio.com support in gitutils
CatalystCode/spk pull request #252
Opened 2020-02-04 23:50 UTC by evanlouie

- Support for visualstudio.com git repository parsing has been added to
  `getRepositoryName`, `getRepositoryUrl`, and `getPullRequestLink`

fixes https://github.com/microsoft/bedrock/issues/928

2020-02-04 23:59 UTC, bnookala approved these changes

2020-02-05 00:12 UTC, mtarng requested changes

2020-02-05 00:12 UTC, mtarng commented on src/lib/gitutils.test.ts
> +      "foobar@vs-ssh.visualstudio.com:v3/some-org/some-project/some-repo";
this is a ssh url

2020-02-05 00:18 UTC, evanlouie commented on src/lib/gitutils.test.ts
> +      "foobar@vs-ssh.visualstudio.com:v3/some-org/some-project/some-repo";
fixed

2020-02-05 00:20 UTC, mtarng approved these changes

2020-02-05 00:29 UTC, merged