Refactoring helper.ts to use only exported methods
CatalystCode/spk pull request #28
Opened 2019-09-26 20:45 UTC by samiyaakhtar

Following the `const export` rule
Closes https://github.com/microsoft/bedrock/issues/608

2019-09-26 21:15 UTC, edaena approved these changes

2019-09-26 21:26 UTC, samiyaakhtar commented on src/commands/deployment/get.test.ts
> +import * as Get from "./get";
Having to do `import * as <something> from ...` because `jest.spyOn` only takes in a name of a module, and not an exported const member

2019-09-26 23:39 UTC, sarath-p requested changes
Looks good. Few comments on docs and async.

2019-09-26 23:39 UTC, sarath-p commented on src/commands/deployment/get.ts
> +import { clusterPipeline, config, hldPipeline, srcPipeline } from "./init";
I think line 5 and 6 can be merged. If you are using all exported methods from ./init, _import *_ is another option.

2019-09-26 23:39 UTC, sarath-p commented on src/commands/deployment/get.ts
> + */
please add docs/comments for all parameters. How about adding _async_ support for this and other methods in this file.

2019-09-26 23:39 UTC, sarath-p commented on src/commands/deployment/get.ts
> +export const printDeployments = (
Similar to above to add comments for parameters.

2019-09-27 17:52 UTC, evanlouie approved these changes
yay for no classes 👍

2019-09-27 18:21 UTC, sarath-p approved these changes
Looks great!

2019-09-27 18:22 UTC, merged