[DESIGN] Exception handling proposal
CatalystCode/spk pull request #382
Opened 2020-03-09 19:12 UTC by dennisseah

2020-03-09 22:23 UTC, andrebriggs approved these changes

2020-03-10 16:50 UTC, yradsmikham requested changes

2020-03-10 16:50 UTC, yradsmikham commented on technical-docs/designs/exceptionHandling.md
> +Reader of the code has a hard time understand why error is ignored.
"understanding" ..?

2020-03-10 16:50 UTC, yradsmikham commented on technical-docs/designs/exceptionHandling.md
> +software and/or from Microsoft's client API (e.g. from Azure DevOps).
"third party software"?

2020-03-10 16:50 UTC, yradsmikham commented on technical-docs/designs/exceptionHandling.md
> +authorization failures too.
"authenticate" and "authorize"?

2020-03-10 16:50 UTC, yradsmikham commented on technical-docs/designs/exceptionHandling.md
> +The proposal is to have a way to maintain this exception chain; and preserving
"preserve"

2020-03-10 16:50 UTC, yradsmikham commented on technical-docs/designs/exceptionHandling.md
> +And this JSON shall be `stringified` and logged as `error` in the finally output
"final"

2020-03-10 16:51 UTC, dennisseah commented on technical-docs/designs/exceptionHandling.md
> +Reader of the code has a hard time understand why error is ignored.
accept

2020-03-10 16:51 UTC, dennisseah commented on technical-docs/designs/exceptionHandling.md
> +software and/or from Microsoft's client API (e.g. from Azure DevOps).
accept

2020-03-10 16:51 UTC, dennisseah commented on technical-docs/designs/exceptionHandling.md
> +authorization failures too.
accept

2020-03-10 16:51 UTC, dennisseah commented on technical-docs/designs/exceptionHandling.md
> +The proposal is to have a way to maintain this exception chain; and preserving
accept

2020-03-10 16:52 UTC, dennisseah commented on technical-docs/designs/exceptionHandling.md
> +And this JSON shall be `stringified` and logged as `error` in the finally output
accept.
thanks

2020-03-10 23:18 UTC, mtarng approved these changes

2020-03-10 23:20 UTC, yradsmikham approved these changes

2020-03-10 23:40 UTC, merged