Deleting .bedrock after infra tests run, fixing test failures
CatalystCode/spk pull request #46
Opened 2019-10-03 21:18 UTC by mtarng

this seems to make the tests more consistent on my machine.

2019-10-03 21:27 UTC, evanlouie requested changes

2019-10-03 21:27 UTC, evanlouie commented on src/commands/infra/create.test.ts
> +    exec("rm", ["-rf", ".bedrock"]);
Can we use `shelljs`'s rm function instead? this wont work on a windows machine

2019-10-03 22:41 UTC, evanlouie approved these changes

2019-10-04 22:55 UTC, bnookala approved these changes

2019-10-04 22:56 UTC, samiyaakhtar approved these changes

2019-10-04 22:58 UTC, merged