Removing TODOs in deploymenttable.ts
CatalystCode/spk pull request #527
Opened 2020-04-07 22:52 UTC by samiyaakhtar

Closes https://github.com/microsoft/bedrock/issues/1301

2020-04-08 00:13 UTC, evanlouie approved these changes

2020-04-08 01:20 UTC, andrebriggs requested changes
Pending sync to discuss this area

2020-04-08 21:09 UTC, yradsmikham approved these changes

2020-04-08 21:27 UTC, mtarng reviewed
Looks like we can probably also remove `/* eslint-disable @typescript-eslint/no-use-before-define */` from `deploymenttable.ts` at this time.

2020-04-08 22:33 UTC, mtarng approved these changes

2020-04-08 22:39 UTC, dennisseah approved these changes

2020-04-09 16:27 UTC, andrebriggs approved these changes

2020-04-09 16:49 UTC, merged