Update the getting started documentation.
CatalystCode/spk pull request #66
Opened 2019-10-14 21:38 UTC by edaena

2019-10-16 00:22 UTC, samiyaakhtar approved these changes

2019-10-16 17:49 UTC, sarath-p requested changes
Looks good. One minor comment to improve the user experience.

2019-10-16 17:49 UTC, sarath-p commented on README.md
> +To specify private keys or access tokens that should **not be stored in raw
I would add a link to `.env.example` file and explain all environment variables in the example file are expected to be configured by the user.

2019-10-17 00:08 UTC, andrebriggs approved these changes
Fix conflicts but looks good.

2019-10-17 00:16 UTC, merged