add script to bump package version
CatalystCode/spk pull request #68
Opened 2019-10-15 00:39 UTC by mydiemho

1. Developer can use this script to update `package.json` and push to a new branch
1. Once this branch is merge, they can manually 
    * run `yarn build` to generate the `dist` directory with the 3 binaries
    * manually create a release on GitHub

2019-10-15 07:08 UTC, bnookala requested changes
@mydiemho per https://github.com/microsoft/bedrock/issues/651#issuecomment-541832442, I wrote i added some requirements - would like to see those addressed.

2019-10-15 07:08 UTC, bnookala commented on package.json
> +  "version": "1.0.0-0",
We should start this from 0.1.0

2019-10-15 17:14 UTC, mydiemho commented on package.json
> +  "version": "1.0.0-0",
@bnookala Depends on how you want to version this. 

## Option 1

Using `1.0.0-0`, you can bump up each pre-release like this
* 1.0.0-1
* 1.0.0-2

and when you're ready, doing a non pre-release, you'll get 1.0.0

## Option 2

Starting at 0.1.0, you're probably thinking of going from
* 0.1.0 => 0.2.0 => 0.3.0

2019-10-16 00:03 UTC, mydiemho commented
will open new pr with pipeline

2019-10-16 00:03 UTC, closed without merging