HLD Pipelines Support
CatalystCode/spk pull request #72
Opened 2019-10-16 00:24 UTC by mtarng

closes https://github.com/microsoft/bedrock/issues/648

2019-10-16 00:29 UTC, mtarng commented
Will do Documentation

2019-10-16 00:51 UTC, andrebriggs commented
> Will do Documentation

@mtarng in this PR?

2019-10-16 16:31 UTC, bnookala commented
@andrebriggs documentation is present in this PR, yeah

2019-10-16 18:46 UTC, andrebriggs requested changes

2019-10-16 18:46 UTC, andrebriggs commented on src/commands/hld/README.md
> +Initialize a Bedrock HLD(High Level Definition) repository and deploy pipelines
@mtarng spacing between HLD and parenthesis

2019-10-16 18:46 UTC, andrebriggs commented on src/commands/hld/README.md
> +1. The access token being utilized via `spk` has access to both repositories.
Not sure if we tell folks how to generate tokens. Maybe a link to https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops

2019-10-16 20:15 UTC, mydiemho commented on src/commands/hld/README.md
> +# HLD
nit: I would also include the full HLD name here

2019-10-16 20:24 UTC, mydiemho commented on src/commands/hld/init.test.ts
> +    // Create random directory to initialize
recommend using `mockfs` when testing directory/file creation.

Here's an example on how to use `mockfs` https://github.com/CatalystCode/spk/blob/57bc476ced54b586e6e3b77390ba713d8f5f0b53/src/lib/fileutils.test.ts

2019-10-16 22:49 UTC, mtarng commented
Ugh, trying to fix this commit mess.

2019-10-17 05:17 UTC, evanlouie approved these changes

2019-10-17 15:57 UTC, andrebriggs approved these changes

2019-10-17 17:28 UTC, merged